### ISSUE TITLE
Services lose get parameters after mirroring

### ISSUE THREAD

**Issue by Magnum5234** [Webysther/packagist-mirror#101]
Get parameters in services are lost during the mirroring:

```
# https://packagist.org/packages.json
search: "https://packagist.org/search.json?q=%query%&type=%type%",

# mirrored version
search: "https://packagist.org/search.json"
```

I think the issue is in `src/Provider.php`
(not tested myself yet.)
https://github.com/Webysther/packagist-mirror/blob/9c6d9b4a735d59fd34616f346359228d222b84ad/src/Provider.php#L109-L119
It seems to me that during `path_url` only the path itself is kept, get parameters are lost.

**Comment by zhaofeng-shu33** [comment]
This is only a static file mirror. Obviously it does not support query parameter.
