### ISSUE TITLE
Question about blocked address for dst download url.

### ISSUE THREAD

**Issue by wudi** [Webysther/packagist-mirror#11]
Seek solutions.

As we know the mirror only download metadata with JSON file.
Passed the first step, then download zipball for code from `dst` field in metadata.
But the `dst` download url blocked too in China. eg. https://api.github.com/xx

Can your have some solutions for the case?

**Comment by webysther** [comment]
Actually no. But this mirror create a github api proxy (mirror?) too, look the code here:

https://github.com/jinfeijie/packagist-mirror/pull/10/files

The mirror: https://php.composer.jinfeijie.cn/

You not fixed yeat?

**Comment by webysther** [comment]
Hi @wudi, any news?

**Comment by wudi** [comment]
> Actually no. But this mirror create a github api proxy (mirror?) too, look the code here:
> 
> https://github.com/jinfeijie/packagist-mirror/pull/10/files
> 
> The mirror: https://php.composer.jinfeijie.cn/
> 
> You not fixed yeat?

this bad idea. because it will occur invalid hash of json file.
i had write a script to rehash all json file.

Steps:
- replace domain in `package$hash.json`
- get new hash package json
- replace old hash to new in providers-xx.json
- get new hash of providers-xx.json
- replace old hash to new in top packages.json

**Comment by webysther** [comment]
After consideration about China block keep this issue open to plan how to do this as a simple option. Thanks @wudi 

Any ideias of @klzsysy @jinfeijie @cnpkg are very welcome! :)

**Comment by webysther** [comment]
Global CDN you be a more simple and fix the problem.
