### ISSUE TITLE
Storage and access

### ISSUE THREAD

**Issue by estahn** [Webysther/packagist-mirror#16]
@Webysther Thanks for this project.

1. I'm still trying to work out the differences between this and satis. Is `packagist-mirror` "just" enabling a geographical close copy while satis has a larger scope?
2. In terms of architecture, would the result of `packagist-mirror` just be pushed to S3 and served via something like Cloudflare?

**Comment by webysther** [comment]
1. Yes, only a mirror.
2. Packagist have a few copy with CDN but some places they don't provide support, like Brazil or China. After some discussion [here](https://github.com/composer/packagist/issues/574) we created a active project to support only mirror to not depend only of packagist.org metadata

**Comment by estahn** [comment]
I see, thanks @Webysther. I was thinking about creating one mirror for Australia, but it appears we should be good if a CDN is used.

**Comment by webysther** [comment]
I prefer webhook to register mirror or rsync protocol like apt mirror. If packagist.org provide global wide CDN reduce the existence of this project, but some places need a copy because github is blocked like [china new mirror](https://php.cnpkg.org/)

**Comment by webysther** [comment]
@estahn you need to ask [packagist](https://github.com/composer/packagist) to create or you can change this repository to push to S3. I do no if the AWS API requests is more cheap than a micro instance for 1 sec sync.
