### ISSUE TITLE
Error - Impossible to create the root directory 

### ISSUE THREAD

**Issue by sdamo** [Webysther/packagist-mirror#21]
An error "Impossible to create the root directory" occurred during the installation.

> $ cd public/p
> $ ls -1 | wc -l 
>   32825
> $

This is a limit subfolder on OS. Can do subfolder of the form **public/p/0/...**, **public/p/1/..**, ... , **public/p/z/..** 

I don’t want to switch to ZFS. Knowledge of PHP is still not enough to do it yourself.

OS: FreeBSD 12 (i386 and amd64)
FileSystem: UFS

**Comment by webysther** [comment]
Wow, shit. :( 
This model is a replica of main mirror, i can't change this, but i can simulate this situation to create using symlink to more normalized structure, as you said.

Is possible to use docker? Look at this: https://github.com/Webysther/packagist-mirror-docker

**Comment by webysther** [comment]
With docker ins't possible to use UFS: https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems

**Comment by webysther** [comment]
Maybe is that limitation you talk about https://docs.oracle.com/cd/E19120-01/open.solaris/819-2723/fsfilesysappx-5/index.html

> Maximum Number of UFS Subdirectories
The maximum number of subdirectories per directory in a UFS file system is **32,767**. This limit is predefined and cannot be changed.

**Comment by webysther** [comment]
Sorry @sdamo but [packagist don't support today this file system](https://github.com/composer/packagist/issues/990), o recommend to use a modern one to solve your problem.
