### ISSUE TITLE
JSON encrypted/compressed over HTTPS

### ISSUE THREAD

**Issue by cwilby** [Webysther/packagist-mirror#4]
After deploying this app to a DigitalOcean droplet I was able to connect my local composer instance and install dependencies.

After enabling HTTP on the server using LetsEncrypt, composer is no longer able to fetch `package.json` as it appears encrypted/compressed.

I have tried enabling/disabling gzip to no avail.

Update: the file is encrypted/encoded on the server when opened with `sudo nano package.json`.

**Comment by cwilby** [comment]
This is the output I get:

```
Composer version 1.6.5 2018-05-04 11:44:59


  [Seld\JsonLint\ParsingException]
  "" does not contain valid JSON
  Parse error on line 1:
  composer
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['


config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...```

**Comment by webysther** [comment]
Hi @cameronwilby, there a feature, i lack to explain on a tutorial to create your own mirror, next few days i fixed this problem.

The mirror creation save all data as .gz to save disk space, you need to enable reverse gz decode when a client ask for the decompressed version.

To do this, change you nginx configuration of **gzip_static** and **gunzip** as is:

```
server {
    index.html;

    server_name packagist.com.br www.packagist.com.br;

    location / {
        try_files $uri $uri/ =404;
        gzip_static on;
        gunzip on;
    }
}
```

Source:
http://nginx.org/en/docs/http/ngx_http_gunzip_module.html
http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

**Comment by cwilby** [comment]
@Webysther that did the trick, thank you!  Here is the nginx config I ended up with:

```
server {
	listen 80;
	listen [::]:80;

	root /var/www/html;
	index index.php index.html index.htm;

	server_name packagist.com.br;

	location / {
		try_files $uri $uri/ =404;
		gzip_static on;
		gunzip on;
	}

	error_page 404 /404.html;
	error_page 500 502 503 504 /50x.html;
	location = /50x.html {
		root /usr/share/nginx/html;
	}

	location ~ \.php$ {
	        include snippets/fastcgi-php.conf;
        	fastcgi_pass unix:/run/php/php7.2-fpm.sock;
	}

	listen [::]:443 ssl ipv6only=on
	listen 443 ssl;
	ssl_certificate /etc/letsencrypt/live/packagist.com.br/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/packagist.com.br/privkey.pem;
	include /etc/letsencrypt/options-ssl-nginx.conf;
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
```

**Comment by webysther** [comment]
Great @cameronwilby! Another tip is using a machine with 2GB at least of memory. With that all metadata keep to the memory helping the nginx and disk to not be consumed.

**Comment by cwilby** [comment]
Good to know, I went with the 2GB droplet on DigitalOcean :+1: Thanks again @Webysther, awesome work.
