### ISSUE TITLE
Not Downloading Meta information properly 

### ISSUE THREAD

**Issue by varunsridharan** [Webysther/packagist-mirror#54]
Today morning i setup a digitalocean server to mirror packages in my nearby country / place

but it stopped downloading files after 2015
![image](https://user-images.githubusercontent.com/1884287/57509917-154e1880-7323-11e9-9606-ca2656e71896.png)

and to download meta for (2013,2014,2015) it almost took around 4+ hrs and sometimes the process just kills it self. i need to do it manually :-(

**Comment by webysther** [comment]
There a possible problem on your server configuration, creating a mirror few minutes ago:

![Captura de tela de 2019-05-10 06-51-53](https://user-images.githubusercontent.com/750007/57518766-334e5580-72f0-11e9-86a5-ea71cc8e72ac.png)

But there some solutions:

1. Use docker with my mirror on DATA_MIRROR [here](https://github.com/Webysther/packagist-mirror-docker):
```bash
-e DATA_MIRROR=https://packagist.jp,https://packagist.phpindonesia.id,https://packagist.kr,https://packagist.com.br
```
2. Change the max connections per mirror:
```bash
-e MAX_CONNECTIONS 25
```

**Comment by varunsridharan** [comment]
@Webysther i even tried with docker. its not working. also i am new to docker. so i am happy to use this method.

**Comment by varunsridharan** [comment]
@Webysther i run on Digitalocean 5$ Plan which provides 1VCPU & 1GB RAM with 25GB HDD

**Comment by webysther** [comment]
ok, on digitalocean with this configuration works well, follow this steps:
- Create a machine on digital ocean, use this 1-click apps: https://marketplace.digitalocean.com/apps/docker
- create a cronjob: https://www.digitalocean.com/community/tutorials/how-to-use-cron-to-automate-tasks-on-a-vps
- put this schedule:
```bash
* * * * * root docker run --name mirror --rm -v /var/www/html:/public -e MAINTAINER_REPO='mymirror.com' webysther/packagist-mirror
```
The vm is new or have another services inside?

**Comment by varunsridharan** [comment]
@Webysther Well its a new server.

**Comment by varunsridharan** [comment]
@Webysther sorry i am not that good @ docker. please help me on this.

**Comment by webysther** [comment]
ok, this weekend I create a tutorial to build a vanila and docker scenario, step-by-step. I send you a message when I finish.

**Comment by webysther** [comment]
#10

**Comment by varunsridharan** [comment]
Awesome Thanks :-) but the in mean time can u give me some ideas  on where could be the issue ?

**Comment by webysther** [comment]
This is a issue, but not a bug, lack of documentation to help you. There some requirements to do on vm, maybe look at #4

**Comment by varunsridharan** [comment]
@Webysther i already did but can't find anything.! :-(

**Comment by varunsridharan** [comment]
and by the way i am using Apache not Nginx

**Comment by webysther** [comment]
There no apache support, apache needs invert gz/raw files delivery, only nginx support this feature.

**Comment by varunsridharan** [comment]
oops.

**Comment by varunsridharan** [comment]
from morning i was trying to get this done !! using apache. !!

**Comment by varunsridharan** [comment]
@Webysther here is the steps to setup a new mirror

## Below Steps only for Server Running in Digitalocean (LEMP Stack)
1. Create A Nginix Server
2. run apt-get update
3. run apt-get install unzip
4. run apt-get install php-mbstring
5. run apt-get install php-simplexml
6. run apt-get install composer
7. cd /var/www/
8. run git clone https://github.com/Webysther/packagist-mirror.git
9. cd packagist-mirror
10. composer install --no-dev
11. cp .env.example .env 
And the configure your .env file

i will keep updating here.

**Comment by varunsridharan** [comment]
@Webysther Using Nginix worked.

**Comment by varunsridharan** [comment]
@Webysther how to setup a cron ?

**Comment by webysther** [comment]
> * create a cronjob: https://www.digitalocean.com/community/tutorials/how-to-use-cron-to-automate-tasks-on-a-vps
> * put this schedule:
> 
> ```shell
> * * * * * root docker run --name mirror --rm -v /var/www/html:/public -e MAINTAINER_REPO='mymirror.com' webysther/packagist-mirror
> ```

Here

**Comment by varunsridharan** [comment]
@Webysther never mind i launched it. here is the new mirror site https://packagist.in/
