### ISSUE TITLE
Sync Packes More Frequent.

### ISSUE THREAD

**Issue by varunsridharan** [Webysther/packagist-mirror#55]
Hi There How i can sync packages more frequent ?

Like very 20 or 30 seconds ?

**Comment by webysther** [comment]
yes, the code is optmized to sync until every 1 sec.

Add a cronjob with this command:

`
while sleep 1; do php bin/mirror create --no-progress; done
`

This code wait 1 sec and run update of metadata. This snippet stay on [docker version](https://github.com/Webysther/packagist-mirror-docker/blob/master/Dockerfile)

**Comment by varunsridharan** [comment]
ok thanks. lets say i created a new composer package. 
https://packagist.org/packages/varunsridahran/testing

And i push an update to `dev-master` and in few sec i am keep on trying to get the updated data in my mirror but it takes around 1min to update my mirror even if i keep on trying `php bin/mirror create` and also my local composer takes around 3mins to update that package.

**Comment by webysther** [comment]
Sometimes, if the main mirror has a big update the mirror takes a litle bit more:

- 1 min to works with composer on main mirror
- 1 sec to 1 min to update on local mirror if you use using `while sleep 1`

The best way is using webhooks, today the main mirror dont support send webhooks of updated packages. Using this method the time can be less than 10 sec to update on all.

To make you mirror shine like a diamond with great performance, use a server with a minimum 2GB of RAM:

- 128MB System
- 256MB Max usage PHP (~15MB)
- 1GB to keep almost all files on memory cache of OS.
