### ISSUE TITLE
Build a miror behind a proxy

### ISSUE THREAD

**Issue by fredbcode** [Webysther/packagist-mirror#58]
Hello,

Unless I missed something, but I can't build a mirror behind a proxy 
In streamhandler.php there is a dns request with php_network_getaddress() 

The proxy works well with env and curl export https_proxy=http://X.X.X.X:port

This feature could be very useful inside company without direct internet access

**Comment by fredbcode** [comment]
Replace https://my-proxy-server:8080 with tcp://my-proxy-server:8080 works

**Comment by webysther** [comment]
Can you send a PR to demonstrate or post a snipet code?

**Comment by fredbcode** [comment]
Just an proxy export is needed in shell

export http_proxy=tcp://my-proxy-server:8080
export https_proxy=tcp://my-proxy-server:8080

This syntax is unusual (http_proxy=http://my-proxy-server:8080 works usualy)

**Comment by webysther** [comment]
Thanks!
