### ISSUE TITLE
Warning: failed to open stream: Too many open file

### ISSUE THREAD

**Issue by helingfeng** [Webysther/packagist-mirror#59]
Warning: include(/packagist-mirror/vendor/league/flysystem/src/FileNotFoundException.php): failed to open stream: Too many open file

```shell
$ ulimit -n
$ ulimit -n 8192
```

**Comment by webysther** [comment]
Are you using inside docker or bare metal vm?

**Comment by helingfeng** [comment]
$ ulimit -n
$ ulimit -n 8192
