### ISSUE TITLE
How I can use an internal domain ?

### ISSUE THREAD

**Issue by fredbcode** [Webysther/packagist-mirror#62]
When I tried to build a mirror with an internal DNS name, the composer request is broken because packages.json contains repo.packagist.org 

I can use mydomain.int as mirror ?

**Comment by fredbcode** [comment]
Nobody uses packagist-mirror without packagist.org as domain name ?

**Comment by fredbcode** [comment]
A despicable workaround ...

unzip packages.json.gz 
sed -i 's/repo.packagist.org/myinternaldomain.int' packages.json

**Comment by varunsridharan** [comment]
@fredbcode i am using this package and also have a domain http://packagist.in/

**Comment by fredbcode** [comment]
http://packagist.in/ is an existing internet domain

My goal is mirroring packagist in an internal infrastructure with 
internal domain

Varun, What do you have in packages.json ?

**Comment by varunsridharan** [comment]
@fredbcode you man installing it in ur local system to mirror ?

**Comment by fredbcode** [comment]
Yes I want mirroring packagist.org for users without internet access 
I can now with this workaround https://github.com/Webysther/packagist-mirror/issues/62#issuecomment-496124959

packages.json contains "hardcoded" urls to internet domain name

**Comment by varunsridharan** [comment]
@fredbcode ok got it but the thing is this mirror script will not fully download every package in ur local / server . this requires an active internet connection. this mirror is there just to provide an quicker access to the downloadable content.

**Comment by fredbcode** [comment]
You mean Internet access for user or mirror ? My mirror is connected to internet,  the users don't

There are 2.2 Go of datas (zipped) in my local server, so how this script select data collected or not ?

**Comment by varunsridharan** [comment]
@fredbcode this script collects data as a JSON and here you can see an example
https://packagist.in/p/varunsridharan/php-autoloader$43f855e12f3936742ebfe87275273239884f61acefeaa20fedefb270637696c3.json

that json is for this package https://packagist.org/packages/varunsridharan/php-autoloader

this script dose not download the sourcecode into local it just provides a link on where to download

**Comment by fredbcode** [comment]
Doh ! So packagist is not really a php mirror
There is a way to do that ?

**Comment by varunsridharan** [comment]
Yes not a full mirror even packagist.org itself dose not download any packages into local it just provide a link to download.

**Comment by fredbcode** [comment]
Thank you, so there is no way to have a full mirror ? like npm, apt, python, etc ?

**Comment by varunsridharan** [comment]
Well i dont think so . in case if u want to do that it would require around 100s OF GBs

**Comment by webysther** [comment]
> Thank you, so there is no way to have a full mirror ? like npm, apt, python, etc ?

This mirror is only metadata mirror because get all code on local is huge, don't scale with time, we talk about [1.6 million](https://packagist.org/statistics) os versions to be downloaded.

[npm is the only that support this kind of mirror with smart download](https://hub.docker.com/r/folha/npm-proxy-cache), on first call the proxy download and create a cache. 

[apt can point to mirror local too](https://blog.programster.org/set-up-a-local-ubuntu-mirror-with-apt-mirror).

composer create an [automatic local cache](https://getcomposer.org/doc/06-config.md#cache-dir) too, you can work on this.
